import XCTest
@testable import SereinCore

// Independently signed using Python cryptography (RSA PKCS1/SHA256 and P-256/SHA256).
// Test keys were ephemeral and discarded; no private key is included.
final class CRXPackageTests: XCTestCase {
    func testRsaSignatureAndIdentity() throws {
        let package = try CRXPackage.verify(fixture("rsavalid"))
        XCTAssertEqual(package.identity.extensionID, "jbbjdidihiknigflmpkclpbogpjpnkoc")
        XCTAssertEqual(package.identity.format, "CRX3")
        XCTAssertEqual(package.archive.prefix(4), Data([0x50,0x4b,0x03,0x04]))
    }
    func testEcdsaSignatureAndIdentity() throws {
        let package = try CRXPackage.verify(fixture("ecdsavalid"))
        XCTAssertEqual(package.identity.extensionID, "hkiphbnnkigodinfegjaimlgdgcfhhlp")
        XCTAssertEqual(package.identity.format, "CRX3")
        XCTAssertEqual(package.archive.prefix(4), Data([0x50,0x4b,0x03,0x04]))
    }
    func testTamperingAndTruncation() throws {
        let valid = try fixture("rsavalid")
        for offset in [0, 8, 15, valid.count - 25] {
            var data = valid; data[offset] ^= 1
            XCTAssertThrowsError(try CRXPackage.verify(data), "Tampering at \(offset)")
        }
        for size in [0, 11, 30, valid.count - 1] {
            XCTAssertThrowsError(try CRXPackage.verify(Data(valid.prefix(size))))
        }
        var legacy = valid; legacy[4] = 2
        XCTAssertThrowsError(try CRXPackage.verify(legacy))
    }
    func testProofMustMatchIdentityAndEveryProofMustVerify() throws {
        for name in ["rsamismatchedID", "ecdsamismatchedID", "rsainvalidExtraProof", "ecdsainvalidExtraProof"] {
            XCTAssertThrowsError(try CRXPackage.verify(fixture(name)), name)
        }
    }
    private func fixture(_ name: String) throws -> Data { try XCTUnwrap(Data(base64Encoded: Self.fixtures[name]!)) }
    private static let fixtures: [String: String] = [
        "rsavalid": "Q3IyNAMAAABFAgAAEqwECqYCMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuFnjZl0K0CIisrZzJi8h/mHi8NQNEZkKg0d+b6yVTdIDnWRdn5OrM7b/AHcN38bI/rBfb3bb21xYOvsJmhzx3KVlqVvD3uctSyG4bQGrGKy1iOGmD0qvS7v+FFm5x4AVY2L3mcWsdNrfGYit9+6GihmplrWXftSNz1bd6XBxx/E5zbhsQBQktKndtSQIvFsewqjG/sadLUDHQeee/Ilgpz7N8IGEALQiM0sIQCpSgHc8G74EuU2ub0TvsJ0ol7+9a0VEGVKfZ0qd2oDII2wg+KjvFLchFWyvTgTO5IiaBadGOyJjMF/k8GJ8M/PgwlF3wHvYlClxEMcueIvRN9uU/wIDAQABEoACBOomiT+9XaFF6LaMH6D+oTWHSeSY54LwITK9dKqYRpA8ZgSi+yaaKAhylFcQH9ZVqbjpa+r8FbATclRXweweefc9xfNiq9HSLQjUnvcK0WS62DPaESuvO/jjqegCKGD/aWS+FQRDImz4Vdg0m8+au6QT92JnilFc+4p7UD/jbn6JKjR9zAw5lQAvmOww4Ei5O5q3eSJCoP6I3Gx2wDZaZ22trbI7FS/8DDZjoZrAVy/4JOPHJajOU83dvtM0yT0YXcL67lCCumiA5PpLVMhq2Fzsdb4byqMdn8xNR9ZYeuL+DKbxaM6Zv1tBHBeAHtXZLZO3HKfc7LfLthyqRe2mtILxBBIKEJEZODh4rYZbz6K/Hm+f2uJQSwMEFAAAAAgAAAA+XR5RlwFiAAAAfgAAAA0AAABtYW5pZmVzdC5qc29uPYzRCkBAEEV/RfdZIm9efYIP0LRmNWFWu0tK/t1KPN7TOffEQiqWQ+x39kGcoqlzKC2MBp2MykNm5YibZ+T4HVRFmfbAwXhZ48tap9G7eU5JeMuVzEQjZ6kTK4Ye8bsrcN1QSwECFAMUAAAACAAAAD5dHlGXAWIAAAB+AAAADQAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QuanNvblBLBQYAAAAAAQABADsAAACNAAAAAAA=",
        "rsamismatchedID": "Q3IyNAMAAABFAgAAEqwECqYCMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuFnjZl0K0CIisrZzJi8h/mHi8NQNEZkKg0d+b6yVTdIDnWRdn5OrM7b/AHcN38bI/rBfb3bb21xYOvsJmhzx3KVlqVvD3uctSyG4bQGrGKy1iOGmD0qvS7v+FFm5x4AVY2L3mcWsdNrfGYit9+6GihmplrWXftSNz1bd6XBxx/E5zbhsQBQktKndtSQIvFsewqjG/sadLUDHQeee/Ilgpz7N8IGEALQiM0sIQCpSgHc8G74EuU2ub0TvsJ0ol7+9a0VEGVKfZ0qd2oDII2wg+KjvFLchFWyvTgTO5IiaBadGOyJjMF/k8GJ8M/PgwlF3wHvYlClxEMcueIvRN9uU/wIDAQABEoACrwFkBPjMXoVdWf/8G3JP4ReNFxTBaRiQ8ATbGudNEd8xol9FzCIZnafqhMaw+wOplzj9UFpbrDi7Ivy/kROpUzLYbBrbRalOAlsubNzx/U5/a3v/zACkgosIw1ylCeBaEMLZz11O5tP12b1F/2w3ELDExO5sOOB4cMQcgtQi6IlrVGJoqT1kjbjBZu+CUbT0LqHXuaTv2Hr7Q0p2ttlekUHLR7JEDXlmcYyesCdPYC+lS7FKoBNIdWa8rcONl9kR+LKPrM9JMnIhU2AkPMLQUFMQS1MkLPbiCnYNDzGbYoCeipQT+kYdACh2bGuVGFqSSFV/zkpEk7imHVMM/PM3MILxBBIKEAAAAAAAAAAAAAAAAAAAAABQSwMEFAAAAAgAAAA+XR5RlwFiAAAAfgAAAA0AAABtYW5pZmVzdC5qc29uPYzRCkBAEEV/RfdZIm9efYIP0LRmNWFWu0tK/t1KPN7TOffEQiqWQ+x39kGcoqlzKC2MBp2MykNm5YibZ+T4HVRFmfbAwXhZ48tap9G7eU5JeMuVzEQjZ6kTK4Ye8bsrcN1QSwECFAMUAAAACAAAAD5dHlGXAWIAAAB+AAAADQAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QuanNvblBLBQYAAAAAAQABADsAAACNAAAAAAA=",
        "rsainvalidExtraProof": "Q3IyNAMAAAB0BAAAEqwECqYCMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuFnjZl0K0CIisrZzJi8h/mHi8NQNEZkKg0d+b6yVTdIDnWRdn5OrM7b/AHcN38bI/rBfb3bb21xYOvsJmhzx3KVlqVvD3uctSyG4bQGrGKy1iOGmD0qvS7v+FFm5x4AVY2L3mcWsdNrfGYit9+6GihmplrWXftSNz1bd6XBxx/E5zbhsQBQktKndtSQIvFsewqjG/sadLUDHQeee/Ilgpz7N8IGEALQiM0sIQCpSgHc8G74EuU2ub0TvsJ0ol7+9a0VEGVKfZ0qd2oDII2wg+KjvFLchFWyvTgTO5IiaBadGOyJjMF/k8GJ8M/PgwlF3wHvYlClxEMcueIvRN9uU/wIDAQABEoACBOomiT+9XaFF6LaMH6D+oTWHSeSY54LwITK9dKqYRpA8ZgSi+yaaKAhylFcQH9ZVqbjpa+r8FbATclRXweweefc9xfNiq9HSLQjUnvcK0WS62DPaESuvO/jjqegCKGD/aWS+FQRDImz4Vdg0m8+au6QT92JnilFc+4p7UD/jbn6JKjR9zAw5lQAvmOww4Ei5O5q3eSJCoP6I3Gx2wDZaZ22trbI7FS/8DDZjoZrAVy/4JOPHJajOU83dvtM0yT0YXcL67lCCumiA5PpLVMhq2Fzsdb4byqMdn8xNR9ZYeuL+DKbxaM6Zv1tBHBeAHtXZLZO3HKfc7LfLthyqRe2mtILxBBIKEJEZODh4rYZbz6K/Hm+f2uISrAQKpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4WeNmXQrQIiKytnMmLyH+YeLw1A0RmQqDR35vrJVN0gOdZF2fk6sztv8Adw3fxsj+sF9vdtvbXFg6+wmaHPHcpWWpW8Pe5y1LIbhtAasYrLWI4aYPSq9Lu/4UWbnHgBVjYveZxax02t8ZiK337oaKGamWtZd+1I3PVt3pcHHH8TnNuGxAFCS0qd21JAi8Wx7CqMb+xp0tQMdB5578iWCnPs3wgYQAtCIzSwhAKlKAdzwbvgS5Ta5vRO+wnSiXv71rRUQZUp9nSp3agMgjbCD4qO8UtyEVbK9OBM7kiJoFp0Y7ImMwX+TwYnwz8+DCUXfAe9iUKXEQxy54i9E325T/AgMBAAESgAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUEsDBBQAAAAIAAAAPl0eUZcBYgAAAH4AAAANAAAAbWFuaWZlc3QuanNvbj2M0QpAQBBFf0X3WSJvXn2CD9C0ZjVhVrtLSv7dSjze0zn3xEIqlkPsd/ZBnKKpcygtjAadjMpDZuWIm2fk+B1URZn2wMF4WePLWqfRu3lOSXjLlcxEI2epEyuGHvG7K3DdUEsBAhQDFAAAAAgAAAA+XR5RlwFiAAAAfgAAAA0AAAAAAAAAAAAAAIABAAAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAEAAQA7AAAAjQAAAAAA",
        "ecdsavalid": "Q3IyNAMAAAC/AAAAGqYBClswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATWHGqrt7fgGv5LANpgZoQwVlFq35Y5pSkhXwtOBE0glXB4YMYXUUirUxEkNDlsDaG5YXPJfv4RMBeO3V++rbscEkcwRQIhAOa3kcJLIURHgOCdSsFVK3ZVO/Rw2aKogXywEWK5o8JpAiB5M40s/eN7Ctm5TlsqXXJpRHNlY6Vg22xx40IXQJQetoLxBBIKEHqPcd2objjVRpCMtjYld79QSwMEFAAAAAgAAAA+XR5RlwFiAAAAfgAAAA0AAABtYW5pZmVzdC5qc29uPYzRCkBAEEV/RfdZIm9efYIP0LRmNWFWu0tK/t1KPN7TOffEQiqWQ+x39kGcoqlzKC2MBp2MykNm5YibZ+T4HVRFmfbAwXhZ48tap9G7eU5JeMuVzEQjZ6kTK4Ye8bsrcN1QSwECFAMUAAAACAAAAD5dHlGXAWIAAAB+AAAADQAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QuanNvblBLBQYAAAAAAQABADsAAACNAAAAAAA=",
        "ecdsamismatchedID": "Q3IyNAMAAAC+AAAAGqUBClswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATWHGqrt7fgGv5LANpgZoQwVlFq35Y5pSkhXwtOBE0glXB4YMYXUUirUxEkNDlsDaG5YXPJfv4RMBeO3V++rbscEkYwRAIgbnfR6kHoDsN6FYOvyRyjWCL5MIzwMmTDcZYll0hb4XsCICgA7LnI62JrMGqeFAm9L0HnhnlBXQhepPzROPYZdeBOgvEEEgoQAAAAAAAAAAAAAAAAAAAAAFBLAwQUAAAACAAAAD5dHlGXAWIAAAB+AAAADQAAAG1hbmlmZXN0Lmpzb249jNEKQEAQRX9F91kib159gg/QtGY1YVa7S0r+3Uo83tM598RCKpZD7Hf2QZyiqXMoLYwGnYzKQ2bliJtn5PgdVEWZ9sDBeFnjy1qn0bt5Tkl4y5XMRCNnqRMrhh7xuytw3VBLAQIUAxQAAAAIAAAAPl0eUZcBYgAAAH4AAAANAAAAAAAAAAAAAACAAQAAAABtYW5pZmVzdC5qc29uUEsFBgAAAAABAAEAOwAAAI0AAAAAAA==",
        "ecdsainvalidExtraProof": "Q3IyNAMAAABqAQAAGqcBClswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATWHGqrt7fgGv5LANpgZoQwVlFq35Y5pSkhXwtOBE0glXB4YMYXUUirUxEkNDlsDaG5YXPJfv4RMBeO3V++rbscEkgwRgIhAIegxl6Bi4FqW/Xh9yNq0Y3cdDdReCt0u0JskelbQHs7AiEAtD+Uz6lOxS3qW5h5fXHQcDBHqfJcYeh1/97POjGPW/+C8QQSChB6j3HdqG441UaQjLY2JXe/GqcBClswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATWHGqrt7fgGv5LANpgZoQwVlFq35Y5pSkhXwtOBE0glXB4YMYXUUirUxEkNDlsDaG5YXPJfv4RMBeO3V++rbscEkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQSwMEFAAAAAgAAAA+XR5RlwFiAAAAfgAAAA0AAABtYW5pZmVzdC5qc29uPYzRCkBAEEV/RfdZIm9efYIP0LRmNWFWu0tK/t1KPN7TOffEQiqWQ+x39kGcoqlzKC2MBp2MykNm5YibZ+T4HVRFmfbAwXhZ48tap9G7eU5JeMuVzEQjZ6kTK4Ye8bsrcN1QSwECFAMUAAAACAAAAD5dHlGXAWIAAAB+AAAADQAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QuanNvblBLBQYAAAAAAQABADsAAACNAAAAAAA=",
    ]
}
