import XCTest
@testable import SereinCore

// Independently signed using Python cryptography (RSA PKCS1/SHA256 and P-256/SHA256).
// Test keys were ephemeral and discarded; no private key is included.
final class CRXPackageTests: XCTestCase {
    func testRsaSignatureAndIdentity() throws {
        let package = try CRXPackage.verify(fixture("rsavalid"))
        XCTAssertEqual(package.identity.extensionID, "jdjdppfoigpghpgeopnpdogcnihnmfnl")
        XCTAssertEqual(package.identity.format, "CRX3")
        XCTAssertEqual(package.archive.prefix(4), Data([0x50,0x4b,0x03,0x04]))
    }
    func testEcdsaSignatureAndIdentity() throws {
        let package = try CRXPackage.verify(fixture("ecdsavalid"))
        XCTAssertEqual(package.identity.extensionID, "ehknhegfcibpimjlfmoifmhlknepcmod")
        XCTAssertEqual(package.identity.format, "CRX3")
        XCTAssertEqual(package.archive.prefix(4), Data([0x50,0x4b,0x03,0x04]))
    }
    func testTamperingAndTruncation() throws {
        let valid = try fixture("rsavalid")
        for offset in [0, 8, 15, valid.count - 25] {
            var data = valid; data[offset] ^= 1
            XCTAssertThrowsError(try CRXPackage.verify(data), "Tampering at \(offset)")
        }
        for size in [0, 11, 30, valid.count - 1] {
            XCTAssertThrowsError(try CRXPackage.verify(Data(valid.prefix(size))))
        }
        var legacy = valid; legacy[4] = 2
        XCTAssertThrowsError(try CRXPackage.verify(legacy))
    }
    func testProofMustMatchIdentityAndEveryProofMustVerify() throws {
        for name in ["rsamismatchedID", "ecdsamismatchedID", "rsainvalidExtraProof", "ecdsainvalidExtraProof"] {
            XCTAssertThrowsError(try CRXPackage.verify(fixture(name)), name)
        }
    }
    private func fixture(_ name: String) throws -> Data { try XCTUnwrap(Data(base64Encoded: Self.fixtures[name]!)) }
    private static let fixtures: [String: String] = [
        "rsavalid": "Q3IyNAMAAABFAgAAEqwECqYCMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA10/68ovLWea9J1uWe14ypEuKMt5XtrFt0g81aLYmuZZmFbL5pIpcwtoCrcKsGnsQJ1chNFMlvIpCGZtagOz8AO0PgzSndWgZHeOogKZ/RI3q2NC1veHOx1I2N7YAmPGiNglr9wmjehNoEyT7cZKpMomqUYfAv8jlaSs8PhQvQ6vuvnHr83JHjWNdzLZ5mhtoG+Yon5+oobtqaqo4LSyNzcOf2/CrG/KGEorI14rDsllUG/xWLRNUj6146XX8GQ9rfMCdsTchBeaaMthWfT05jBStLocIiX4/tMmc7tiUliZ/rWur27UxZjORZdmpvDHRVHJwR7oJW0aXdSEe2NH/YwIDAQABEoACxgGFa6kTKGzKA6IjB219O+c2fZQYy7mkhurB5prjDLRMkBxt6+j1yBiVCorNSVyfM/1o6uLMjFJDWkdjeB+MN2rZRRzNjEwfs7ebvwudMf11gZjmWuRfqzYaOWXNfR+dcQ+fL/PHICRon9Z1hCZEWeDZWTSYXpg1D6oy85A0HUMohBxamm1j5r3aaRi2QPvgLNoQ67DCBZE5CFXqIZSseqUYJvPxjb0jpe8bD+0iBbQCfCWfkMR0OZX9+nSOC4XtMAK9mW+n+/jJ+HV+H6QRYKzNExT6757udN5Jq6IClQPzv4VeK/9ZZG1wAQSp6kQrcM1tCqFrX7IctQJtrDY6y4LxBBIKEJOT/16G9n9k798+Yth9xdtQSwMEFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAABtYW5pZmVzdC5qc29uq1bKTczLTEstLokvSy0qzszPU7Iy1lHKS8xNVbJSCs5Mz0tNUUjLrCgpLUpV0lGCq1Ey1DNQqgUAUEsBAhQDFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAAAAAAAAAAAAAIABAAAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAEAAQA7AAAAZAAAAAAA",
        "rsamismatchedID": "Q3IyNAMAAABFAgAAEqwECqYCMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA10/68ovLWea9J1uWe14ypEuKMt5XtrFt0g81aLYmuZZmFbL5pIpcwtoCrcKsGnsQJ1chNFMlvIpCGZtagOz8AO0PgzSndWgZHeOogKZ/RI3q2NC1veHOx1I2N7YAmPGiNglr9wmjehNoEyT7cZKpMomqUYfAv8jlaSs8PhQvQ6vuvnHr83JHjWNdzLZ5mhtoG+Yon5+oobtqaqo4LSyNzcOf2/CrG/KGEorI14rDsllUG/xWLRNUj6146XX8GQ9rfMCdsTchBeaaMthWfT05jBStLocIiX4/tMmc7tiUliZ/rWur27UxZjORZdmpvDHRVHJwR7oJW0aXdSEe2NH/YwIDAQABEoACR9OFllrj3Mf12oWAaVArNkeyud3og6Tt8yz1bzZ4Fi5PYPbjeqQTlvxURYLdqVDBHg6cpYgnMW4lKiHVGB1G+wgpvy1Gdh53rMaUmFbieN7HGinqHPrrYel3t5x3H3WgK8Lpq13tOWLxccEuwo0JYwHtiZaSZ+eassosRkLeGpmaI8Hk1OOyEVkjjseolkog94C8kPOMTAva7IEAk9Uy6+sZq7CDfmYekWXBJcBH9491QRwlHU2DCnQMUy2DQGP4NIHzgD/GYu+1WQCWTTzmIyz/AmQS4Y2wUIHZek+dZrS4xnF+q3c4HznLB0Osjp2WDykK2XqLz75L65DpqyhcOoLxBBIKEAAAAAAAAAAAAAAAAAAAAABQSwMEFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAABtYW5pZmVzdC5qc29uq1bKTczLTEstLokvSy0qzszPU7Iy1lHKS8xNVbJSCs5Mz0tNUUjLrCgpLUpV0lGCq1Ey1DNQqgUAUEsBAhQDFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAAAAAAAAAAAAAIABAAAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAEAAQA7AAAAZAAAAAAA",
        "rsainvalidExtraProof": "Q3IyNAMAAAB0BAAAEqwECqYCMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA10/68ovLWea9J1uWe14ypEuKMt5XtrFt0g81aLYmuZZmFbL5pIpcwtoCrcKsGnsQJ1chNFMlvIpCGZtagOz8AO0PgzSndWgZHeOogKZ/RI3q2NC1veHOx1I2N7YAmPGiNglr9wmjehNoEyT7cZKpMomqUYfAv8jlaSs8PhQvQ6vuvnHr83JHjWNdzLZ5mhtoG+Yon5+oobtqaqo4LSyNzcOf2/CrG/KGEorI14rDsllUG/xWLRNUj6146XX8GQ9rfMCdsTchBeaaMthWfT05jBStLocIiX4/tMmc7tiUliZ/rWur27UxZjORZdmpvDHRVHJwR7oJW0aXdSEe2NH/YwIDAQABEoACxgGFa6kTKGzKA6IjB219O+c2fZQYy7mkhurB5prjDLRMkBxt6+j1yBiVCorNSVyfM/1o6uLMjFJDWkdjeB+MN2rZRRzNjEwfs7ebvwudMf11gZjmWuRfqzYaOWXNfR+dcQ+fL/PHICRon9Z1hCZEWeDZWTSYXpg1D6oy85A0HUMohBxamm1j5r3aaRi2QPvgLNoQ67DCBZE5CFXqIZSseqUYJvPxjb0jpe8bD+0iBbQCfCWfkMR0OZX9+nSOC4XtMAK9mW+n+/jJ+HV+H6QRYKzNExT6757udN5Jq6IClQPzv4VeK/9ZZG1wAQSp6kQrcM1tCqFrX7IctQJtrDY6y4LxBBIKEJOT/16G9n9k798+Yth9xdsSrAQKpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDXT/ryi8tZ5r0nW5Z7XjKkS4oy3le2sW3SDzVotia5lmYVsvmkilzC2gKtwqwaexAnVyE0UyW8ikIZm1qA7PwA7Q+DNKd1aBkd46iApn9EjerY0LW94c7HUjY3tgCY8aI2CWv3CaN6E2gTJPtxkqkyiapRh8C/yOVpKzw+FC9Dq+6+cevzckeNY13MtnmaG2gb5iifn6ihu2pqqjgtLI3Nw5/b8Ksb8oYSisjXisOyWVQb/FYtE1SPrXjpdfwZD2t8wJ2xNyEF5poy2FZ9PTmMFK0uhwiJfj+0yZzu2JSWJn+ta6vbtTFmM5Fl2am8MdFUcnBHuglbRpd1IR7Y0f9jAgMBAAESgAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUEsDBBQAAAAIAAAAPl2tRpB5OQAAAD4AAAANAAAAbWFuaWZlc3QuanNvbqtWyk3My0xLLS6JL0stKs7Mz1OyMtZRykvMTVWyUgrOTM9LTVFIy6woKS1KVdJRgqtRMtQzUKoFAFBLAQIUAxQAAAAIAAAAPl2tRpB5OQAAAD4AAAANAAAAAAAAAAAAAACAAQAAAABtYW5pZmVzdC5qc29uUEsFBgAAAAABAAEAOwAAAGQAAAAAAA==",
        "ecdsavalid": "Q3IyNAMAAAC/AAAAGqYBClswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARIHBEDnR0rXXgPV7P2FXfQtSNZEE3tyWLjoEOIvU+9dvqK5KfMOlexB3O9CNOCJJXne07NAgdXiMuI8JNRArQ4EkcwRQIhAPAwXW3VwKv1Nwo8MHVVA/0qbDEGGHQuiQfKU6BEoOs9AiBAKA493DCoBbryd55NiRq5ctew4jaNi/2sh9syOXdeIoLxBBIKEEetdGUoH4ybXOhce61PLONQSwMEFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAABtYW5pZmVzdC5qc29uq1bKTczLTEstLokvSy0qzszPU7Iy1lHKS8xNVbJSCs5Mz0tNUUjLrCgpLUpV0lGCq1Ey1DNQqgUAUEsBAhQDFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAAAAAAAAAAAAAIABAAAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAEAAQA7AAAAZAAAAAAA",
        "ecdsamismatchedID": "Q3IyNAMAAAC/AAAAGqYBClswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARIHBEDnR0rXXgPV7P2FXfQtSNZEE3tyWLjoEOIvU+9dvqK5KfMOlexB3O9CNOCJJXne07NAgdXiMuI8JNRArQ4EkcwRQIhAKTWdp2vlwnkm9Hw6F5ZyIEpWH/9KL/2fxJCzYWXAxHgAiAsvVPUEGwzeZfmkvau/M5ncgZTAPUYU9qq2AayUwzoTILxBBIKEAAAAAAAAAAAAAAAAAAAAABQSwMEFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAABtYW5pZmVzdC5qc29uq1bKTczLTEstLokvSy0qzszPU7Iy1lHKS8xNVbJSCs5Mz0tNUUjLrCgpLUpV0lGCq1Ey1DNQqgUAUEsBAhQDFAAAAAgAAAA+Xa1GkHk5AAAAPgAAAA0AAAAAAAAAAAAAAIABAAAAAG1hbmlmZXN0Lmpzb25QSwUGAAAAAAEAAQA7AAAAZAAAAAAA",
        "ecdsainvalidExtraProof": "Q3IyNAMAAABoAQAAGqYBClswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARIHBEDnR0rXXgPV7P2FXfQtSNZEE3tyWLjoEOIvU+9dvqK5KfMOlexB3O9CNOCJJXne07NAgdXiMuI8JNRArQ4EkcwRQIgQkX/EviJuAyMh6XS5TRMpOlI5aYYFnBeZ+JEM5rnfNUCIQC2SEtLhrpXd+DobjzgV4BBR/EJSMZPzcAYS3PzVtzAIoLxBBIKEEetdGUoH4ybXOhce61PLOMapgEKWzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEgcEQOdHStdeA9Xs/YVd9C1I1kQTe3JYuOgQ4i9T712+orkp8w6V7EHc70I04Ikled7Ts0CB1eIy4jwk1ECtDgSRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUEsDBBQAAAAIAAAAPl2tRpB5OQAAAD4AAAANAAAAbWFuaWZlc3QuanNvbqtWyk3My0xLLS6JL0stKs7Mz1OyMtZRykvMTVWyUgrOTM9LTVFIy6woKS1KVdJRgqtRMtQzUKoFAFBLAQIUAxQAAAAIAAAAPl2tRpB5OQAAAD4AAAANAAAAAAAAAAAAAACAAQAAAABtYW5pZmVzdC5qc29uUEsFBgAAAAABAAEAOwAAAGQAAAAAAA==",
    ]
}
